services:
  metabase:
    container_name: metabase
    hostname: metabase
    image: metabase/metabase:latest
    networks: ['shared_network']
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    restart: always
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=${PSQL_PWD}
      - MB_DB_HOST=postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:17
    networks: ['shared_network']
    restart: always
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=${PSQL_PWD}
      - POSTGRES_DB=metabase
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U metabase -d metabase']
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true